name: C++ DevOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-lint-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install required tools
      run: |
        sudo apt update
        sudo apt install -y g++ make cppcheck gcovr clang-format

    - name: Build C++ project
      run: |
        make

    - name: Run tests
      run: |
        make test

    - name: Run linter (cppcheck)
      run: |
        bash scripts/lint.sh

    - name: Run coverage report
      run: |
        python3 scripts/coverage.py

    - name: Upload Coverage Report Artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: build/coverage.html
