stages:
  - build
  - test
  - lint
  - coverage

variables:
  BUILD_DIR: build/

before_script:
  - apt update && apt install -y g++ make cppcheck gcovr clang-format python3

build:
  stage: build
  script:
    - make

test:
  stage: test
  script:
    - make test

lint:
  stage: lint
  script:
    - bash scripts/lint.sh

coverage:
  stage: coverage
  script:
    - python3 scripts/coverage.py
  artifacts:
    paths:
      - ${BUILD_DIR}/coverage.html
