stages:
  - build
  - lint
  - test
  - coverage

variables:
  DEBIAN_FRONTEND: noninteractive


build:
  stage: build
  script:
    - chmod +x scripts/build.sh
    - ./scripts/build.sh


lint:
  stage: lint
  script:
    - apt-get update && apt-get install -y cppcheck
    - chmod +x scripts/lint.sh
    - ./scripts/lint.sh


test:
  stage: test
  before_script:
    - apt-get update && apt-get install -y cmake libgtest-dev lcov
    - cd /usr/src/gtest
    - cmake .
    - make
    - cp lib/*.a /usr/lib
    - cd $CI_PROJECT_DIR
  script:
    - g++ -std=c++11 -o tests/test_main tests/test_main.cpp -lgtest -lgtest_main -pthread -fprofile-arcs -ftest-coverage
    - ./tests/test_main
    - find . -name "*.gcda"
  artifacts:
    paths:
      - '**/*.gcda'
      - '**/*.gcno'
      - '**/*.cpp'
      - '**/*.h'
    when: always
    expire_in: 1h


coverage:
  stage: coverage
  before_script:
    - apt-get update && apt-get install -y lcov
  script:
    - echo "Checking for coverage files"
    - find . -name "*.gcno"
    - find . -name "*.gcda"
    - lcov --directory . --capture --output-file coverage.info
    - lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info
    - genhtml coverage.info --output-directory coverage_report
  artifacts:
    paths:
      - coverage.info
      - coverage_report/
    expire_in: 1h
